name: CI Tests

on: [push, pull_request]

jobs:
  GNU:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        compiler: [gfortran]

    env:
      FC: ${{ matrix.compiler }}

    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install Cmake
        run: pip3 install cmake

      - name: Install python dependencies
        run: pip3 install numpy pytest

      - name: Install blas, lapack and other dependencies
        run: sudo apt-get install libgmp10 libgmpxx4ldbl libgmp-dev 

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
